#include <stdio.h>
#include <stdlib.h>
#include <ncurses.h>
#include <unistd.h>
#include <sys/time.h>
#include <math.h>
#include <time.h>
#include "struct.h"
#include "print_image.h"
#include "set_color.h"
#include "menu.h"
#include "objects.h"
#include "play.h"
#include "get_key.h"
#include "move_airplane.h"
#include "border.h"
#include "score_board.h"
#include "end_game.h"
#include "logs.h"
#include "get_name.h"
#include "level.h"
#include "add_effect.h"