#include <stdio.h>
#include <stdlib.h>
#include <ncurses.h>
#include <unistd.h>
#include <sys/time.h>
#include <math.h>
#include <time.h>
#include "struct/struct.h"
#include "tools/print_image.h"
#include "tools/set_color.h"
#include "menu/menu.h"
#include "play/objects.h"
#include "play/play.h"
#include "tools/get_key.h"
#include "play/move_airplane.h"
#include "play/border.h"
#include "play/score_board.h"
#include "end_game/end_game.h"
#include "log/logs.h"
#include "end_game/get_name.h"
#include "level/level.h"
#include "play/add_effect.h"
#include "level/level_value.h"